version: '3'
services:

  db-video-storage:
    image: mongo:4.2.8
    container_name: db-video-storage
    ports:
      - "4040:27017"
    restart: "always"

  db-stream-history:
    image: mongo:4.2.8
    container_name: db-stream-history
    ports:
      - "4041:27017"
    restart: "always"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: DockerfilePROD
    container_name: video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db-video-storage:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: DockerfilePROD
    container_name: video-storage
    env_file:
      - ./azure-storage/.env.local
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: "no"

  stream-history:
    image: stream-history
    build:
      context: ./stream-history
      dockerfile: DockerfilePROD
    container_name: stream-history
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db-stream-history:27017
      - DBNAME=stream-history
    restart: "no"
