version: '3'
services:

  db-video-storage:
    image: mongo:4.2.8
    container_name: db-video-storage
    ports:
      - "4040:27017"
    restart: "always"

  db-stream-history:
    image: mongo:4.2.8
    container_name: db-stream-history
    ports:
      - "4041:27017"
    restart: "always"

  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: DockerfileDEV
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db-video-storage:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    env_file:
      - ./video-streaming/.env.local
    restart: "no"

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: DockerfileDEV
    container_name: video-storage
    volumes:
      - /tmp/azure-storage/npm-cache:/root/.npm:z
      - ./azure-storage/src:/usr/src/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    env_file:
      - ./azure-storage/.env.local
    restart: "no"

  stream-history:
    image: stream-history
    build:
      context: ./stream-history
      dockerfile: DockerfileDEV
    container_name: stream-history
    volumes:
      - /tmp/stream-history/npm-cache:/root/.npm:z
      - ./stream-history/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db-stream-history:27017
      - DBNAME=stream-history
    env_file:
      - ./stream-history/.env.local
    restart: "no"

  recommendations:
    image: recommendations
    build:
      context: ./recommendations
      dockerfile: DockerfileDEV
    container_name: recommendations
    volumes:
      - /tmp/recommendations/npm-cache:/root/.npm:z
      - ./recommendations/src:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    env_file:
      - ./recommendations/.env.local
    restart: "no"
